"""create initial tables

Revision ID: c06b98bbe6de
Revises: 
Create Date: 2026-09-27 05:01:34.913719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c06b98bbe6de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adopters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_adopters_id'), 'adopters', ['id'], unique=False)
    op.create_table('shelters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shelters_id'), 'shelters', ['id'], unique=False)
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('species', sa.Enum('DOG', 'CAT', 'BIRD', 'REPTILE', name='species'), nullable=False),
    sa.Column('breed', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('adopted', sa.Boolean(), nullable=True),
    sa.Column('shelter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shelter_id'], ['shelters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_id'), 'animals', ['id'], unique=False)
    op.create_table('adoption_interests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adopter_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='adoptionstatus'), nullable=False),
    sa.ForeignKeyConstraint(['adopter_id'], ['adopters.id'], ),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adoption_interests_id'), 'adoption_interests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adoption_interests_id'), table_name='adoption_interests')
    op.drop_table('adoption_interests')
    op.drop_index(op.f('ix_animals_id'), table_name='animals')
    op.drop_table('animals')
    op.drop_index(op.f('ix_shelters_id'), table_name='shelters')
    op.drop_table('shelters')
    op.drop_index(op.f('ix_adopters_id'), table_name='adopters')
    op.drop_table('adopters')
    # ### end Alembic commands ###
